blank_issues_enabled: false
contact_links:
  - name: Documentation / Usage / FAQ
    url: https://pyscaffold.org/
    about: Inform yourself about the usage of PyScaffold on the official website
  - name: Discussions
    url: https://github.com/pyscaffold/pyscaffold/discussions
    about: Ask questions, find answers and discuss with other PyScaffold community members
